name: .NET Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Set up directories
      run: |
        mkdir Dalamud
        mkdir Mogmog
    - name: Checkout Dalamud
      uses: actions/checkout@v2
      with:
        repository: goaaats/Dalamud
        path: Dalamud
        submodules: recursive
    - name: Install dependencies for Dalamud
      run: |
        cd Dalamud
        dotnet restore
    - name: Build Dalamud .NET 4
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
         .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dalamud\Dalamud.sln /t:Build /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE
    - name: Checkout Mogmog
      uses: actions/checkout@v2
      with:
        path: Mogmog
    - name: Install dependencies for Mogmog
      run: |
        cd Mogmog
        dotnet restore
    - name: Build Mogmog
      run: |
        cd Mogmog
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd Mogmog
        dotnet test --no-restore --verbosity normal
