name: .NET Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up directories
      run: mkdir Dalamud
         | mkdir Mogmog
    - name: Change directory to Dalamud
      run: cd Dalamud
    - name: Checkout Dalamud
      uses: actions/checkout@v2
      with:
        repository: goaaats/Dalamud
    - name: Change directory to Mogmog
      run: cd ../Mogmog
    - name: Checkout Mogmog
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
